### ISSUE TITLE
Emby插件无法加载

### ISSUE THREAD

**Issue by MATRIX06060** [kookxiang/jellyfin-plugin-bangumi#110]
**版本**
docker emby 4.7.14.0
使用的lovechen/embyserver镜像
插件使用CI版本 1.5.71构建
已经确认权限没有问题
**日志文件如下**
[embyserver.txt](https://github.com/kookxiang/jellyfin-plugin-bangumi/files/14391661/embyserver.txt)

**Comment by kookxiang** [comment]
#108 这里的要求 emby 4.8.0.80 以上版本

**Comment by MATRIX06060** [comment]
那麻烦问一下还有老版本的吗，CI的已经没了

**Comment by MATRIX06060** [comment]
希望以后可以把CI的弄到release来，这样也方便找老版本

**Comment by kookxiang** [comment]
https://ci.appveyor.com/project/kookxiang/jellyfin-plugin-bangumi/builds/49261668
重新触发了一下，等会可以在这下载

**Comment by MATRIX06060** [comment]
谢谢
