### ISSUE TITLE
[Feature Request] 简介能否加个保留html换行符缩进的选项？

### ISSUE THREAD

**Issue by deadblue0910** [kookxiang/jellyfin-plugin-bangumi#112]
~~挤成一坨不是很美观~~
![2024-03-12_20-11-24](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/48860218/3727487c-927d-4aaf-8d4d-14538dcdba10)
![2024-03-12_20-17-13](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/48860218/6dc28d1b-48ed-4205-967a-436aa95a0172)

**Comment by kookxiang** [comment]
可以加个开关
