### ISSUE TITLE
bangumi episode id识别正确但却没有metadata？

### ISSUE THREAD

**Issue by xht8723** [kookxiang/jellyfin-plugin-bangumi#124]
如题，有人知道是为什么吗？
右键使用插件identify之后，封面片名简介等都没问题。
但是单独的一集，简介之类的没有，甚至标题也没有。
这个情况有时候发生有时候又没有....搞不清发生规律。
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/15156436/7f4abf89-aece-49a7-8207-6529ee34ca2f)
<img width="1235" alt="Untitled2" src="https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/15156436/6cb888e2-aa7f-455e-ac71-23d2a78e9dc3">
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/15156436/4b15e8a8-6d7d-424d-b4fa-aa674ddb0703)

**Comment by xht8723** [comment]
似乎是因为identify无法覆盖原先旧有的.nfo内容.....只要把.nfo删光，再右键replace all metadata就可以了。
应该是jellyfin的问题，不是很懂为什么......挺奇怪的。

然后这次更新jellyfin之后我还发现很多片的名字串了....我的EVA点开来名字叫异世界开挂药师....
太迷啦jellyfin.....

**Comment by kookxiang** [comment]
是的，很神奇，我测试用的环境没遇到，给 NAS 升级以后也遇到了

感觉像是新版本数据迁移有问题，等官方修复吧，可以通过删 nfo 临时解决
```shell
find . -type f -name "*.nfo" -delete
```
