### ISSUE TITLE
Jellyfin 无法授权登录

### ISSUE THREAD

**Issue by TheAriaki** [kookxiang/jellyfin-plugin-bangumi#128]
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/37679939/5f3f9371-b2aa-4534-9cd5-c13152877ff6)

**Comment by Y4M4M0M0** [comment]
我也遇到这个情况了 不知道咋办

**Comment by kookxiang** [comment]
https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/runs/9121318213
可以试试这个版本，或者手动加下  Plugins 前缀
稍后我发个更新

**Comment by Y4M4M0M0** [comment]
> https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/runs/9121318213 可以试试这个版本，或者手动加下 Plugins 前缀 稍后我发个更新

搞定了 这个链接的能用 谢了老哥
