### ISSUE TITLE
所有剧集都被识别为最后的一集

### ISSUE THREAD

**Issue by BiancoChiu** [kookxiang/jellyfin-plugin-bangumi#130]
Jellyfin版本：10.9.4
Bangumi版本：1.6.1.0

<img width="1058" alt="Screenshot 2024-06-06 at 7 27 36 PM" src="https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/108531014/027d47c1-0f7a-43ff-aa6a-616c9d4cb093">
<img width="728" alt="Screenshot 2024-06-06 at 7 31 02 PM" src="https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/108531014/3cbfbe5c-17fa-4ec2-9c00-78ee04e3d94a">

**Comment by kookxiang** [comment]
10.9.4 的 bug，我试了 10.9.5 已经解决

**Comment by BiancoChiu** [comment]
感谢，好快的回复！
