### ISSUE TITLE
无法延长授权时间或者取消授权

### ISSUE THREAD

**Issue by Izumiko** [kookxiang/jellyfin-plugin-bangumi#137]
Jellyfin是官方Docker最新版10.9.7，插件版本是1.6.1。
![图片](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/5195868/9fd2c95d-506e-44a3-8d75-d714b36bc351)
今天看番时发现没有和Bangumi同步进度，到插件这里点击延长提示已更新，点击取消授权确认后无提示。无论是哪个，刷新页面后上边的状态均无变化，且Jellyfin日志中无任何相关信息。

删除`plugins/configurations/Jellyfin.Plugin.Bangumi.OAuth.dat`，然后重启重新授权后才成功更新授权，但依旧无法延长或是取消。

**Comment by kookxiang** [comment]
看下日志中有没有报错？

**Comment by Izumiko** [comment]
我重启完Jellyfin，然后在插件里面操作，再在日志界面点开之后只有Jellyfin启动时的任务日志，后续没有插件的报错或是其他任何显示，比较奇怪。

还是说需要啥操作让Jellyfin显示更加详细的调试信息？

**Comment by Izumiko** [comment]
刚刚在计划任务里面点了一下“OAuth 登录令牌刷新”，发现过期时间成功延长了，日志里面也有了计划任务运行完成的记录。这样看来只是插件设置页面的两个按钮点击没作用。

**Comment by kookxiang** [comment]
Jellyfin 外面有套类似 nginx 之类的转发层吗？感觉像是 js 的部分报错了，但我这没法复现
点按钮没反应的话按下 F12 看看 Console 里有报错吗

**Comment by Izumiko** [comment]
套了nginx，而且是把Jellyfin代理到了`/jellyfin`这个路径下
console里面没有报错，网络页面返回的状态码也是200

![图片](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/5195868/2f2f8459-bf7b-4273-be07-55473eb22bd0)

**Comment by salomejou** [comment]
授权只有7天，能不能授权永不过期？

**Comment by kookxiang** [comment]
> 授权只有7天，能不能授权永不过期？

会自动续期，另外有问题请新开 issue
