### ISSUE TITLE
对整季或者媒体库使用刷新元数据功能会让单集的季号设置为0，导致显示为特典。对单集使用刷新元数据则能正确获取季号

### ISSUE THREAD

**Issue by HmnSn** [kookxiang/jellyfin-plugin-bangumi#138]
在媒体库节目标签页对整季使用刷新元数据
![1](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/49606244/dcce0b97-d95d-47d0-8ff2-b44da43a63ea)
![2](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/49606244/d373c245-39f9-476d-8adb-de1eaf70dd1e)

单集的季号设置为0，导致显示为特典
![4](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/49606244/c8c05c53-5f7d-4677-9c22-242ec77ac107)
![3](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/49606244/ae3014ef-8b3d-4851-ace2-0944cac2cfa5)

在剧集页对单集使用刷新元数据
![5](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/49606244/51571126-6b38-494b-ad50-9c1003ba49ff)
正确获取季号
![6](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/49606244/b299b19a-fb64-4095-9dc2-cf4e646e17ef)

如果是通过实时监控添加进来的新文件季号能正确获得，但再对整季使用刷新元数据后季号也重置为0

**Comment by kookxiang** [comment]
我试了下没问题，你用的是 10.9.6 之后的版本吗？

**Comment by HmnSn** [comment]
> 我试了下没问题，你用的是 10.9.6 之后的版本吗？

使用的是10.9.7版本，文件目录是”鹿乃子乃子虎视眈眈 (2024)/Season 1/鹿乃子乃子虎视眈眈 (2024) S01E01.mkv“这样的规则。试了下同样目录规则的老的完结的动画，手动刷新后也会置0

**Comment by kookxiang** [comment]
看看 `Season 1` 这层的 metadata 季号对不对？

**Comment by kookxiang** [comment]
可以试试这个版本，临时加了个兼容处理，感觉跟 Season 和 Episode 在 Jellyfin 内部创建先后顺序有关
https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/runs/9860655822

**Comment by HmnSn** [comment]
> 看看 `Season 1` 这层的 metadata 季号对不对？

season.nfo的<seasonnumber>实时监控自动生成和手动刷新元数据都正常为1，对比先后两次的tvshow.nfo、season.nfo和单集nfo，只有最后单集的nfo内容有区别
![1](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/49606244/ed48c250-79b4-47ac-b15a-dd3d2517dd61)

**Comment by HmnSn** [comment]
> 可以试试这个版本，临时加了个兼容处理，感觉跟 Season 和 Episode 在 Jellyfin 内部创建先后顺序有关 https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/runs/9860655822

解决了，现在能正确获得季号
![2](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/49606244/554669fe-8287-4365-8a3c-dd33af2be646)
