### ISSUE TITLE
【BUG】无法正确刮削到剧集和SP

### ISSUE THREAD

**Issue by X012C** [kookxiang/jellyfin-plugin-bangumi#139]
![image](https://github.com/user-attachments/assets/42d4e07e-dd0e-45d1-800b-f0a5bbec2154)
![image](https://github.com/user-attachments/assets/e06fc997-7f6b-4d86-b92f-b758fecaf082)

例如这类条目中分别有SP和EP的时候就会刮削成特典，第0季。

**Comment by kookxiang** [comment]
麻烦提供下文件的路径，我本地试试看

**Comment by X012C** [comment]
> 麻烦提供下文件的路径，我本地试试看
![image](https://github.com/user-attachments/assets/53a75d17-6582-4796-8260-ae4021712e54)

![image](https://github.com/user-attachments/assets/f61ab997-753b-4582-8364-8604f66e01e7)

**Comment by kookxiang** [comment]
可能跟 #138 是同一个问题，在这下载个最新的试试，能好的话我推到仓库上面
https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/workflows/jellyfin.yml

**Comment by X012C** [comment]
> 可能跟 #138 是同一个问题，在这下载个最新的试试，能好的话我推到仓库上面 https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/workflows/jellyfin.yml

通过这个（https://github.com/kookxiang/jellyfin-plugin-bangumi/actions/runs/9860655822）刮削成功，眼花看成它上面的一个，浪费了好多时间。
