### ISSUE TITLE
[Feature Request] 能否对不同番剧自定义文件命名格式以不重命名的情况下准确刮削

### ISSUE THREAD

**Issue by windowBR** [kookxiang/jellyfin-plugin-bangumi#144]
不太想将文件全部改名而是希望留下字幕组在文件名中保留的信息，但因此造成的结果为剧集数识别经常出错
特别是体现在多季的动画中将所有剧集都识别为文件名中的季号
能否提供一个入口自定义每部番剧的文件名格式以实现准确的集数刮削

**Comment by windowBR** [comment]
或者也可以折中一下能否提供手动输入单集的 Bangumi 剧集 ID 然后以此进行单集的刮削，目前的手动重新刮削似乎只能针对整季而不能针对单独的剧集

**Comment by kookxiang** [comment]
提供下有问题的文件名和路径？理论上大部分字幕组的文件名都能直接自动解析

**Comment by windowBR** [comment]
这边主要两部番遇见了比较严重的大批量识别错误的情况
1. 京吹3：路径为(以媒体库设定的文件夹为相对根目录)
/吹响吧！上低音号 Season3/
文件名如：
![image](https://github.com/user-attachments/assets/57694fe3-2c63-424c-a60a-d3c8fa21d3e4)

2. 素晴3：路径为
/为美好的世界献上祝福！ Season3/
文件名：
![image](https://github.com/user-attachments/assets/4f17a6a3-93f1-43d8-b818-fb01eda13d6a)

以上两部番的共同问题体现为前三集识别正常，从第四集到最后一集全部识别为第三集
![image](https://github.com/user-attachments/assets/9a93a7c8-f6fa-4056-ba4b-630636d9459c)

**Comment by kookxiang** [comment]
后台设置关掉 AnitomySharp 以后再用覆盖模式刷新下元数据就好了

**Comment by windowBR** [comment]
尝试了一下后对这两部番确实有效，先就这么用着吧，如果之后的剧集全都能识别正常就不打开 AnitomySharp 了
