### ISSUE TITLE
第6.5集被识别成第6集

### ISSUE THREAD

**Issue by Hitagi-Hu** [kookxiang/jellyfin-plugin-bangumi#147]
物语系列最新季(https://bgm.tv/subject/475354)中出现的问题：
![截图 2024-08-27 01-20-10](https://github.com/user-attachments/assets/c4f949cb-a6a6-40a1-a83d-944b5c6eb4ee)

视频文件命名里集数为 "06.5" ,修改文件名改成"6.5"也同样识别成第6集。
手动编辑该集元数据中的bangumi剧集ID再刷新元数据后能成功识别。
![截图 2024-08-27 01-32-04](https://github.com/user-attachments/assets/4223adc0-fbc9-4dc4-bc59-cacbae98303e)

**Comment by kookxiang** [comment]
麻烦提供下文件的路径，还有后台设置截图

**Comment by Hitagi-Hu** [comment]
> 麻烦提供下文件的路径，还有后台设置截图

文件路径：E:\番剧\物语系列怪物季\[ANi] 物語系列 第外季＆第怪季 - 6.5 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4
插件设置：
![图片](https://github.com/user-attachments/assets/f5d838fd-3e5e-4565-9f4c-f45265897c54)

**Comment by kookxiang** [comment]
<img width="439" alt="image" src="https://github.com/user-attachments/assets/ff9a77c8-b894-4c60-ac83-c5eb109d14ce">
这两个开关换一下试试？

**Comment by Hitagi-Hu** [comment]
> <img alt="image" width="439" src="https://private-user-images.githubusercontent.com/2725379/361787046-ff9a77c8-b894-4c60-ac83-c5eb109d14ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Njk2NDksIm5iZiI6MTcyNDc2OTM0OSwicGF0aCI6Ii8yNzI1Mzc5LzM2MTc4NzA0Ni1mZjlhNzdjOC1iODk0LTRjNjAtYWM4My1jNWViMTA5ZDE0Y2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMTQzNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWY1MGE0ZDJjZTczNDk0ODIwMGUwMjkwZjM0ZDZmNjUxMTBiOTk0YjVmNDE2NzBiZGQyYTczMDU3Mjk2ZmIxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ywr3bEnZrNz5i1J5UBVwOeRCUvklS58DbZxpG4J1Cvk"> 这两个开关换一下试试？

感谢！按照你说的更改设置，删除该集后重新下载，自动识别成功了。
