### ISSUE TITLE
在安卓Emby Server上退出

### ISSUE THREAD

**Issue by o81018o** [kookxiang/jellyfin-plugin-bangumi#148]
将插件添加至/storage/emulated/0/Android/data/com.emby.embyserver/files/plugins/后，emby在启动阶段退出
emby版本4.9.0.30
Android14
日志：
[embyserver-63860537473.txt](https://github.com/user-attachments/files/16792876/embyserver-63860537473.txt)

**Comment by kookxiang** [comment]
像是 mono 相比 .net 少了一些库导致的

我本地试了下，需要降到 .NET Standard 2.1 并且魔改部分代码才能跑

可以拿这个版本玩，不过估计合不进来
[Emby.Plugin.Bangumi.dll.zip](https://github.com/user-attachments/files/16800450/Emby.Plugin.Bangumi.dll.zip)

**Comment by kookxiang** [comment]
> 这个版本依然启动不了，而且合不进来是指什么

我这里是可以的，如果不行麻烦再发下最新的日志？

合不到主干的话后续更新就不能针对这个场景单独打包了

![Screenshot_20240829-223110_Chrome](https://github.com/user-attachments/assets/82aba775-da35-42ec-9fd0-41ac82e9a266)

**Comment by o81018o** [comment]
我刚刚发现我传错文件了，已经能正常启动了，谢谢
