### ISSUE TITLE
能否在剧集介绍信息里显示集数？

### ISSUE THREAD

**Issue by YUUUCC** [kookxiang/jellyfin-plugin-bangumi#149]
例如《义妹生活》，共有12集，现在播放了9集，则显示“9/12”之类的信息

**Comment by kookxiang** [comment]
jellyfin 本身有未看过集数的提示，应该还好？
如果要在简介中作的话可能就得每周刷新元数据，感觉不是很有必要

**Comment by YUUUCC** [comment]
这样的话确实不必进行这个更改，谢谢作者大大
