### ISSUE TITLE
多季番剧获取部分图片失败

### ISSUE THREAD

**Issue by YUUUCC** [kookxiang/jellyfin-plugin-bangumi#151]
### 文件结构
（采取每一季单独放置是因为只要文件夹命名和bangumi一致，就可以自动刮削到正确的信息）

租借女友
├─ S01E01
├─ S01E02

租借女友 第二季
├─ S02E13
├─ S02E14

租借女友 第三季
├─ S03E25
├─ S03E26

### 问题

- 第一季可正常获取背景、缩略、徽标、封面，而非第一季仅可获取封面
- 非第一季每一集的缩略图，有的可以正常获取，有的则是所有集数的缩略图都一样（见下）
![image](https://github.com/user-attachments/assets/aaaf1584-9932-4ab6-be70-51d2184e08bd)
- 非第一季的文件夹内不会生成metadata文件夹，不过不影响图片显示和视频播放

**Comment by kookxiang** [comment]
bgm 的元数据仅包含每季封面图
其它的图片应该是 tmdb 插件返回的
