### ISSUE TITLE
演职人员图片和封面图片无法获取

### ISSUE THREAD

**Issue by dibin666** [kookxiang/jellyfin-plugin-bangumi#17]
如图
![QQ截图20220708220316](https://user-images.githubusercontent.com/44898339/178007507-e759d49f-bf7b-4c13-aaae-c5ec7f3f5fb5.png)
必须手动添加才可以，搜索可以搜索到，但点下载后会一直转圈
![微信图片_20220708220425](https://user-images.githubusercontent.com/44898339/178007764-d9e1a589-a60d-40f3-8c5c-316b1028a678.png)

jellyin版本：10.8.1
jellyfin-plugin-bangumi版本：1.4.7.0

**Comment by kookxiang** [comment]
直接打开 bgm.tv 看图片正常吗？

**Comment by dibin666** [comment]
> 直接打开 bgm.tv 看图片正常吗？

那我知道原因了，好像不挂代理看不了bgm的图片
