### ISSUE TITLE
升级到V1.7.0之后，JellyFin V10.9提示不支持插件

### ISSUE THREAD

**Issue by jones-187** [kookxiang/jellyfin-plugin-bangumi#173]
V1.7.0的日志说兼容V10.9，但好像并不支持

![image](https://github.com/user-attachments/assets/427cef9e-e951-4928-bab0-30f1c7f37a9d)
![image](https://github.com/user-attachments/assets/b7aa783f-822d-4b5c-ae62-1633b970de98)

**Comment by jones-187** [comment]
jelyfin升级到V10.10，插件就能正常启动了

**Comment by kookxiang** [comment]
10.9.0 先从 actions 里下载，之后重新发一次
