### ISSUE TITLE
配置文件辅助刮削番剧

### ISSUE THREAD

**Issue by Rirmach** [kookxiang/jellyfin-plugin-bangumi#176]
#101 中提到了可以在季文件中添加配置文件的方式实现辅助刮削，现在这个功能是否仍然保留？多季番剧的季 ID 识别仍然有很多问题。
本人的番剧下载通过 bangumi + mikan 实现，实际上是先有 ID 后下载番剧的，在文件夹下生成 bangumi ID 是顺势而为的事情，手动设置 ID 反而麻烦。

PS. 能否可以在番剧文件夹下添加同样的配置文件实现番剧的辅助刮削，以及明确和扩充配置文件的格式定义？
PPS. ini 格式仍具有诸多限制，可否采用 yaml，toml 等信息丰富的配置文件格式？

**Comment by kookxiang** [comment]
一直有的，Series 和 Season 都支持，如果不可用可以贴目录结构和日志看看

用 ini 实际上也只是为了偷懒（因为插件引入常用的其它依赖很容易冲突，也不想用 json 这种手写起来麻烦的格式）
现在是直接识别的 `xxx=xxx`，其他的行会忽略

支持的配置：
https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/d652bea5223a92c311cd4e6bd0a40d1ccb7e217d/Jellyfin.Plugin.Bangumi/Model/LocalConfiguration.cs#L10-L14

**Comment by Rirmach** [comment]
> 一直有的，Series 和 Season 都支持，如果不可用可以贴目录结构和日志看看
> 
> 用 ini 实际上也只是为了偷懒（因为插件引入常用的其它依赖很容易冲突，也不想用 json 这种手写起来麻烦的格式） 现在是直接识别的 `xxx=xxx`（忽略大小写），其他的行会忽略
> 
> 支持的配置：
> 
> https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/d652bea5223a92c311cd4e6bd0a40d1ccb7e217d/Jellyfin.Plugin.Bangumi/Model/LocalConfiguration.cs#L10-L14

Offset 和 Report 分别指的是？

**Comment by kookxiang** [comment]
offset 用来给文件名中集号和 bgm 不同时做补正（尤其是分割放送的番比较乱）

report 控制是否上报播放记录到 bgm（比如一些小众里番？）

**Comment by Rirmach** [comment]
> offset 用来给文件名中集号和 bgm 不同时做补正（尤其是分割放送的番比较乱）
> 
> report 控制是否上报播放记录到 bgm（比如一些小众里番？）

请问 Offset 的用法是？比如文件名是 S2E1，bgm 是第 2 季第 13 集，那么 offset 应该是 12 还是 -12？如果文件名是 S2E13 但 bgm 是第 2 季第 1 集又是什么情况呢？

**Comment by kookxiang** [comment]
目前是文件名中的集号减去 offset 值对应 bgm 的集号

比如 E13 对应 bgm E01 的话 offset 为 12
S01 对应 bgm E13 的话 offset 为 -12

**Comment by Rirmach** [comment]
> offset 用来给文件名中集号和 bgm 不同时做补正（尤其是分割放送的番比较乱）
> 
> report 控制是否上报播放记录到 bgm（比如一些小众里番？）

另外还有个问题，配置文件中可设置 report=true 以控制是否上报观看进度，那么是否可能实现接口
```/v0/users/-/collections/{subject_id}``` 
中 private=true 以控制番剧收藏是否可见？

**Comment by kookxiang** [comment]
> 配置文件中可设置 report=true 以控制是否上报观看进度，那么是否可能实现接口
> 
> ```/v0/users/-/collections/{subject_id}``` 
> 
> 中 private=true 以控制番剧收藏是否可见？

可以的，但没有可以交互的点位，只能默认全部隐藏或者可见
如果不想默认可见的话提前收藏一下就好了吧

**Comment by Rirmach** [comment]
感谢，看样子下载管理程序里加上配置文件生成逻辑基本上就能解决刮削识别率的问题
