### ISSUE TITLE
刮削剧集报错

### ISSUE THREAD

**Issue by lzyl42** [kookxiang/jellyfin-plugin-bangumi#177]
刮削零之使魔四季都报错
https://bgm.tv/subject/1880
https://bgm.tv/subject/1103
https://bgm.tv/subject/763
https://bgm.tv/subject/25823

> [15:43:48] [ERR] [82] MediaBrowser.Providers.TV.SeasonMetadataService: Error in Bangumi

>System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Array'.
>   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
>   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
>   at Jellyfin.Plugin.Bangumi.Model.InfoBox.GetString(String key)
>   at Jellyfin.Plugin.Bangumi.Providers.SeasonProvider.GetMetadata(SeasonInfo info, CancellationToken token)
>   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)

**Comment by kookxiang** [comment]
好像复现不了，试试开离线数据库能正常吗？

**Comment by lzyl42** [comment]
更新了新版本同时更新了jellyfin，然后jellyfin崩了_(:з」∠)_ 
最近还不方便去维护，过阵子再试试吧
