### ISSUE TITLE
以非正确Bangumi 季 Id请求导致的刮削失败

### ISSUE THREAD

**Issue by Iannnnnnnnnnnnnnnnn** [kookxiang/jellyfin-plugin-bangumi#183]
jellyfin 10.10.3
bangumi 1.7.0
![c538e4da7574fe66e6ec3fafb6ff42c8](https://github.com/user-attachments/assets/39f69ac5-367b-4445-9172-356be4be5a4b)
文件存储结构，两季都在同一文件夹下
![image](https://github.com/user-attachments/assets/2dd0f80e-2012-4b59-ad39-9add6eb9bdd6)

火影忍者1-220正常刮削（bangumi季id 3425），疾风传221-720 无法自动识别（bangumi季id 2782），手动补充季id后依旧无法识别子集标题。
![image](https://github.com/user-attachments/assets/d268b760-33ac-489f-a977-59133d811055)
![image](https://github.com/user-attachments/assets/84ae653a-a071-4261-958d-f974c1e24bea)
在日志中可以看到，疾风传的标题元数据是以3425作为季id请求导致的刮削失败
- [13:28:06] [INF] [17] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: guess episode number from filename Naruto.Shippuuden.2007.E225.WEB-DL.1080p.H264.AAC-HDCTV.mp4 because of plugin configuration
- [13:28:06] [INF] [17] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: used episode number 225 from anitomy
- [13:28:06] [INF] [17] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: load subject 3425 episode list from archive
- [13:28:06] [INF] [89] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: used episode number 225 from anitomy
- [13:28:06] [INF] [89] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: found matching episode 225 with type null
- [13:28:06] [INF] [89] Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: metadata for Naruto.Shippuuden.2007.E225.WEB-DL.1080p.H264.AAC-HDCTV.mp4: null

**Comment by kookxiang** [comment]
![image](https://github.com/user-attachments/assets/5ee988c0-9fb4-49a8-8a8b-b4f387b3c29e)
有试过关掉这个吗？

另外查询 3425 是正常的，因为需要拿到这个季度下面有哪些集，用来判断识别的集号对不对

**Comment by Iannnnnnnnnnnnnnnnn** [comment]
> 有试过关掉这个吗？
尝试过了，还是不行。
> 另外查询 3425 是正常的，因为需要拿到这个季度下面有哪些集，用来判断识别的集号对不对
但是3425下只有1-220集，2782下只有220-720。结果2782下的剧集就从3425里收集不到元数据。
我只能把修改文件结构让3425和2782独立吗？

**Comment by kookxiang** [comment]
完整的目录结构是怎样的？目前只会判断视频文件的上一级是否为季目录，如果不是的话只能拿到整个系列的 id

**Comment by Iannnnnnnnnnnnnnnnn** [comment]
![image](https://github.com/user-attachments/assets/61cceae9-771f-4c87-af9d-f343947cd804)
![image](https://github.com/user-attachments/assets/808dcb79-1d4f-48c6-8cc7-16afe725b109)

**Comment by kookxiang** [comment]
因为视频的上一级不是季目录，所以插件会直接使用系列（也就是第一季）的 id

如果不想调整目前文件结构可以试试在 ini 中指定一下季 id
https://github.com/kookxiang/jellyfin-plugin-bangumi/wiki/%E9%A2%9D%E5%A4%96%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by Iannnnnnnnnnnnnnnnn** [comment]
解决了✌，谢谢。
