### ISSUE TITLE
死循环？

### ISSUE THREAD

**Issue by Trim21** [kookxiang/jellyfin-plugin-bangumi#19]
今天发现 API 请求数特别多，看了下UA发现不是爬虫。是这个插件的UA在不停的请求同样章节信息。

基本就是`/v0/episodes?subject_id=24823&limit=50&offset=878` 和 `/v0/episodes?subject_id=24823&limit=50&offset=828` 两个链接。

也有可能不是插件的BUG，是有人用了插件的UA。

![image](https://user-images.githubusercontent.com/13553903/179179498-65f91d7b-49c8-4a46-a65d-bac3f8c7a454.png)

**Comment by Trim21** [comment]
暂时先在Nginx加了个请求频率的限制

**Comment by chu-shen** [comment]
加个请求速度限制下？像[anidb](https://github.com/jellyfin/jellyfin-plugin-anidb/blob/170134f235aa7c73aab4c65763213e2d0c2b4d93/Jellyfin.Plugin.AniDB/Providers/AniDB/Metadata/AniDbSeriesProvider.cs#L32)那样

**Comment by kookxiang** [comment]
加延迟有点治标不治本的感觉，未来准备把 https://github.com/bangumi/Archive 接进来

**Comment by Trim21** [comment]
请求频率和请求数问题不大，主要问题死循环了，导致一直在请求相同的东西。

**Comment by kookxiang** [comment]
我理解应该是传入了一个奇怪的 index，导致往前翻和往后翻都找不到这一集，发布更新后就能解决

**Comment by chu-shen** [comment]
早上起来看到429错误还以为bgm这边有限制，没注意是临时措施😓

**Comment by Trim21** [comment]
我把请求速率限制先去掉了，要是再遇到这个bug我直接把对应UA给ban掉好了。
