### ISSUE TITLE
能搞个存储库吗？

### ISSUE THREAD

**Issue by Trim21** [kookxiang/jellyfin-plugin-bangumi#2]
这样就可以自动更新了...

**Comment by kookxiang** [comment]
推到 Github Pages 上了：https://kookxiang.github.io/jellyfin-plugin-bangumi/repository.json
不过不知道为啥 Github Actions 请求 API 会失败，暂时只能本地 build 完上传

**Comment by Trim21** [comment]
https://github.com/bangumi/api/blob/fded3da50eac4d91a6822022b137f46a466d1aaa/.github/workflows/build.yaml#L32
