### ISSUE TITLE
Bangumi 1.4.7.0 狀態：NotSupported

### ISSUE THREAD

**Issue by Arcelibs** [kookxiang/jellyfin-plugin-bangumi#20]
Bangumi 1.4.7.0 狀態：NotSupported
![image](https://user-images.githubusercontent.com/49543451/179232904-098c7129-2177-438c-8aa0-b38657d2e5b0.png)

重新安裝過，還是一樣

![image](https://user-images.githubusercontent.com/49543451/179232975-80181097-3f40-4958-8bff-9ac3d21d63f8.png)

**Comment by kookxiang** [comment]
确保下 Fastenshtein.dll 也在插件目录内
另外最好能提供下启动的日志

**Comment by fuxin052** [comment]
10.8的nyanmisaka/jellyfin有问题, 我之前也搞了好久, 后来换jellyfin/jellyfin就是可以了, 解码效率也没有区别

**Comment by kookxiang** [comment]
之前因为打包原因可能需要 10.8.1 才能运行，非官方库的版本还在 10.8.0，API 有部分不一致报错了，现在打包配置改回来了
