### ISSUE TITLE
无法把进度同步到bangumi

### ISSUE THREAD

**Issue by Trim21** [kookxiang/jellyfin-plugin-bangumi#22]
我在jellyfin这边设置了bangumi的id，然后这jellyfin这边把对应的集标为了在看。但是bangumi这边一直没有更新？

**Comment by kookxiang** [comment]
目前手动标记不会触发同步，未播放的视频播放完成后会自动同步

**Comment by Trim21** [comment]
这个是jellyfin的限制吗

**Comment by kookxiang** [comment]
并不是（
我加个选项放开好了
https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/1c006dc9ef9a565e7ba6a0e8d96224a97d86ae17/Jellyfin.Plugin.Bangumi/PlaybackScrobbler.cs#L48
