### ISSUE TITLE
海贼王 好像不能匹配到epid

### ISSUE THREAD

**Issue by mutsumi63** [kookxiang/jellyfin-plugin-bangumi#25]
show或者season填入 bangumiid后，epid还是获取不到 ，其他好像都能获取到 就海贼王不行

**Comment by kookxiang** [comment]
麻烦提供一下文件名和配置的id

**Comment by mutsumi63** [comment]
> 麻烦提供一下文件名和配置的id

海贼王--S01--E1028.mkv
海贼王--S21--E1028.mkv
好像不能自动识别到bangumi的epid，其他的给tvshow.nfo设置了bangumiid都能自动识别到bangumi的epid

如果改成01季度，imdb trak bangumi都不能获取到epid
如果改成21季度，imdb和trak是能自动读到
bangumi是都算成一个季度，S21获取不到是正常  ，不太清楚这个S01 bangumi的epid为啥获取不到

tvshow.nfo是这样写的
```<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<tvshow>  
  <tmdbid>37854</tmdbid>
  <bangumiid>975</bangumiid>
</tvshow>```

season.nfo中也填了bangumiid

**Comment by mutsumi63** [comment]
![image](https://user-images.githubusercontent.com/4182301/185076466-f45a99dc-abdc-4765-ab38-48385f236fee.png)
Bangumi插件的设置是这样的

**Comment by chu-shen** [comment]
手写的nfo？

### 我这边是jellyfin生成的👇

**tvshow**
```
<tvshow>
  <title>海贼王</title>
  <originaltitle>ONE PIECE</originaltitle>
  <rating>8.4</rating>
  <year>1999</year>
  <mpaa>TV-14</mpaa>
  <imdb_id>tt0388629</imdb_id>
  <tmdbid>37854</tmdbid>
  <premiered>1999-10-20</premiered>
  <releasedate>1999-10-20</releasedate>
  <enddate>1999-10-20</enddate>
  <runtime>24</runtime>
  <tvrageid>8205</tvrageid>
  <bangumiid>975</bangumiid>
  <kitsuid>12</kitsuid>
  <anilistid>21</anilistid>
  <anidbid>69</anidbid>
  <tvdbid>81797</tvdbid>
</tvshow>
```

**海贼王--S21--E1020.mkv**
```
<episodedetails>
  <plot>脚本
    中山智博
……
そして、その声に導かれ、サンジを救出に来たのは――ハナハナの実の能力を使ったニコ・ロビンだった！</plot>
  <lockdata>false</lockdata>
  <dateadded>2022-08-18 08:30:14</dateadded>
  <title>山治惨叫! 响彻全岛的SOS</title>
  <originaltitle>サンジ絶叫! 島中に響くSOS</originaltitle>
  <rating>8</rating>
  <year>2022</year>
  <imdbid>tt20240972</imdbid>
  <tvdbid>9177821</tvdbid>
  <runtime>22</runtime>
  <bangumiid>1084417</bangumiid>
  <kitsuid>280796</kitsuid>
  <showtitle>海贼王</showtitle>
  <episode>1020</episode>
  <season>1</season>
  <aired>2022-06-05</aired>
</episodedetails>
```

### S01和S21其实bangumi都能获取到👇
```
Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use exists episode number 1018 from file name "海贼王--S01--E1018.mkv.mkv"
Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use exists episode number 1027 from file name "海贼王--S21--E1027.mkv.mkv"
```

你要是实在在意，可以尝试：
- 重启jellyfin，然后**多次**刷新海贼王的元数据
- 移除此集，刷新元数据，确认移除后再加回来👉`Removing item, Type: "Episode", Name: "四皇を超えろ ルフィ反撃の鉄拳", Path: "海贼王--S01--E1028.mkv.mp4", Id: 594607e9`

这边建议直接放弃，说不定哪一天它就自动好了🤣

**Comment by mutsumi63** [comment]
> 手写的nfo？
> 
> ### 我这边是jellyfin生成的👇
> **目录**
> 
> ```
> ~/Downloads/新建文件夹
> $ tree -N
> .
> `-- ONE PIECE
>     |-- tvshow.nfo
>     |-- 海贼王--S01--E1018.mkv.mkv
>     |-- 海贼王--S01--E1018.mkv.nfo
>     |-- 海贼王--S01--E1028.mkv.mkv
>     |-- 海贼王--S01--E1028.mkv.nfo
>     |-- 海贼王--S21--E1019.mkv.mkv
>     |-- 海贼王--S21--E1019.mkv.nfo
>     |-- 海贼王--S21--E1020.mkv.mkv
>     |-- 海贼王--S21--E1020.mkv.nfo
>     |-- 海贼王--S21--E1027.mkv.mkv
>     |-- 海贼王--S21--E1027.mkv.nfo
>     |-- 海贼王--S21--E1029.mkv.mkv
>     `-- 海贼王--S21--E1029.mkv.nfo
> ```
> 
> **tvshow**
> 
> ```
> <tvshow>
>   <title>海贼王</title>
>   <originaltitle>ONE PIECE</originaltitle>
>   <rating>8.4</rating>
>   <year>1999</year>
>   <mpaa>TV-14</mpaa>
>   <imdb_id>tt0388629</imdb_id>
>   <tmdbid>37854</tmdbid>
>   <premiered>1999-10-20</premiered>
>   <releasedate>1999-10-20</releasedate>
>   <enddate>1999-10-20</enddate>
>   <runtime>24</runtime>
>   <tvrageid>8205</tvrageid>
>   <bangumiid>975</bangumiid>
>   <kitsuid>12</kitsuid>
>   <anilistid>21</anilistid>
>   <anidbid>69</anidbid>
>   <tvdbid>81797</tvdbid>
> </tvshow>
> ```
> 
> **海贼王--S21--E1020.mkv**
> 
> ```
> <episodedetails>
>   <plot>脚本
>     中山智博
> ……
> そして、その声に導かれ、サンジを救出に来たのは――ハナハナの実の能力を使ったニコ・ロビンだった！</plot>
>   <lockdata>false</lockdata>
>   <dateadded>2022-08-18 08:30:14</dateadded>
>   <title>山治惨叫! 响彻全岛的SOS</title>
>   <originaltitle>サンジ絶叫! 島中に響くSOS</originaltitle>
>   <rating>8</rating>
>   <year>2022</year>
>   <imdbid>tt20240972</imdbid>
>   <tvdbid>9177821</tvdbid>
>   <runtime>22</runtime>
>   <bangumiid>1084417</bangumiid>
>   <kitsuid>280796</kitsuid>
>   <showtitle>海贼王</showtitle>
>   <episode>1020</episode>
>   <season>1</season>
>   <aired>2022-06-05</aired>
> </episodedetails>
> ```
> 
> ### S01和S21其实bangumi都能获取到👇
> ```
> Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use exists episode number 1018 from file name "海贼王--S01--E1018.mkv.mkv"
> Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: use exists episode number 1027 from file name "海贼王--S21--E1027.mkv.mkv"
> ```
> 
> 你要是实在在意，可以尝试：
> 
> * 重启jellyfin，然后**多次**刷新海贼王的元数据
> * 移除此集，刷新元数据，确认移除后再加回来👉`Removing item, Type: "Episode", Name: "四皇を超えろ ルフィ反撃の鉄拳", Path: "海贼王--S01--E1028.mkv.mp4", Id: 594607e9`
> 
> ~这边建议直接放弃，说不定哪一天它就自动好了🤣~不清楚剧集的元数据是什么一个逻辑，有些番bangumi、imdb都有，有些就只有bangumi

我删了Jellyfin和他的Data文件都清理，整个的数据重新试了也不行 
我季度写文件夹上的 不是写在文件名上

然后还是试了把猜测集数关了好像也不行

日志里有类似信息
`Jellyfin.Plugin.Bangumi.Providers.EpisodeProvider: file "E1029.mkv" has incorrect episode index 1029, set to 1029`

**Comment by chu-shen** [comment]
写文件夹上也是能获取到剧集信息的
```
$ tree
.
`-- ONE PIECE
    |-- S01
    |   |-- E1020.mkv
    |   |-- E1020.nfo
    |   |-- E1027.mkv
    |   |-- E1027.nfo
    |   |-- E1028.mkv
    |   |-- E1028.nfo
    |   `-- season.nfo
    |-- S21
    |   |-- E1029.mkv
    |   |-- E1029.nfo
    |   `-- season.nfo
    `-- tvshow.nfo
```

[写成这样也是能获取到的](https://github.com/kookxiang/jellyfin-plugin-bangumi/wiki/%E5%8F%82%E8%80%83%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84)，优点是第一季里也有bangumi信息
```
|-- Season 1
|   |-- E1020.mkv
|   |-- E1020.nfo
|   |-- E1027.mkv
|   |-- E1027.nfo
|   |-- E1028.mkv
|   |-- E1028.nfo
|   `-- season.nfo
|-- Season 21
|   |-- E1029.mkv
|   |-- E1029.nfo
|   `-- season.nfo
`-- tvshow.nfo
```

### 确认一下

点击番剧信息里的bangumi，看下跳转的是不是这个链接：https://bgm.tv/subject/145691

### 复现

照着我的步骤试下：

1. 新建目录：`~/新建文件夹/ONE PIECE/Season 1/`，先不忙把视频放进去
2. 创建媒体库TEST，位置选`~/新建文件夹`
3. 刷新TEST媒体库，模式选`扫描新的……`
4. 确认TEST媒体库已有海贼王番剧及第一季
5. 将`E1021.mkv`放入第一季目录下👉`~/新建文件夹/ONE PIECE/Season 1/`
6. 在番剧页面刷新元数据，模式选`扫描新的……`
7. 检查是否有bangumi信息

对了，bangumi上1021集前才有本集介绍信息，1022之后没有，估计这里有个判断逻辑，所以EP1028没有bangumi🥲

**Comment by chu-shen** [comment]
写文件夹上也是能获取到剧集信息的
```
$ tree
.
`-- ONE PIECE
    |-- S01
    |   |-- E1020.mkv
    |   |-- E1020.nfo
    |   |-- E1027.mkv
    |   |-- E1027.nfo
    |   |-- E1028.mkv
    |   |-- E1028.nfo
    |   `-- season.nfo
    |-- S21
    |   |-- E1029.mkv
    |   |-- E1029.nfo
    |   `-- season.nfo
    `-- tvshow.nfo
```

[写成这样也是能获取到的](https://github.com/kookxiang/jellyfin-plugin-bangumi/wiki/%E5%8F%82%E8%80%83%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84)，优点是第一季里也有bangumi信息
```
|-- Season 1
|   |-- E1020.mkv
|   |-- E1020.nfo
|   |-- E1027.mkv
|   |-- E1027.nfo
|   |-- E1028.mkv
|   |-- E1028.nfo
|   `-- season.nfo
|-- Season 21
|   |-- E1029.mkv
|   |-- E1029.nfo
|   `-- season.nfo
`-- tvshow.nfo
```

### 确认一下

点击番剧信息里的bangumi，看下跳转的是不是这个链接：https://bgm.tv/subject/145691

### 复现

照着我的步骤试下：

1. 新建目录：`~/新建文件夹/ONE PIECE/Season 1/`，先不忙把视频放进去
2. 创建媒体库TEST，位置选`~/新建文件夹`
3. 刷新TEST媒体库，模式选`扫描新的……`
4. 确认TEST媒体库已有海贼王番剧及第一季
5. 将`E1021.mkv`放入第一季目录下👉`~/新建文件夹/ONE PIECE/Season 1/`
6. 在番剧页面刷新元数据，模式选`扫描新的……`
7. 检查是否有bangumi信息

对了，bangumi上1021集前才有本集介绍信息，1022之后没有，估计这里有个判断逻辑，所以EP1028没有bangumi🥲

**Comment by mutsumi63** [comment]
> 写文件夹上也是能获取到剧集信息的
> 
> ```
> $ tree
> .
> `-- ONE PIECE
>     |-- S01
>     |   |-- E1020.mkv
>     |   |-- E1020.nfo
>     |   |-- E1027.mkv
>     |   |-- E1027.nfo
>     |   |-- E1028.mkv
>     |   |-- E1028.nfo
>     |   `-- season.nfo
>     |-- S21
>     |   |-- E1029.mkv
>     |   |-- E1029.nfo
>     |   `-- season.nfo
>     `-- tvshow.nfo
> ```
> 
> [写成这样也是能获取到的](https://github.com/kookxiang/jellyfin-plugin-bangumi/wiki/%E5%8F%82%E8%80%83%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84)，优点是第一季里也有bangumi信息
> 
> ```
> |-- Season 1
> |   |-- E1020.mkv
> |   |-- E1020.nfo
> |   |-- E1027.mkv
> |   |-- E1027.nfo
> |   |-- E1028.mkv
> |   |-- E1028.nfo
> |   `-- season.nfo
> |-- Season 21
> |   |-- E1029.mkv
> |   |-- E1029.nfo
> |   `-- season.nfo
> `-- tvshow.nfo
> ```
> 
> ### 确认一下
> 点击番剧信息里的bangumi，看下跳转的是不是这个链接：https://bgm.tv/subject/145691
> 
> ### 复现
> 照着我的步骤试下：
> 
> 1. 新建目录：`~/新建文件夹/ONE PIECE/Season 1/`，先不忙把视频放进去
> 2. 创建媒体库TEST，位置选`~/新建文件夹`
> 3. 刷新TEST媒体库，模式选`扫描新的……`
> 4. 确认TEST媒体库已有海贼王番剧及第一季
> 5. 将`E1021.mkv`放入第一季目录下👉`~/新建文件夹/ONE PIECE/Season 1/`
> 6. 在番剧页面刷新元数据，模式选`扫描新的……`
> 7. 检查是否有bangumi信息
> 
> 对了，bangumi上1021集前才有本集介绍信息，1022之后没有，估计这里有个判断逻辑，所以EP1028没有bangumi🥲

subjectid没问题
我试了下，是因为1022之后没简介的引起的，我试着改成1020有bangumi的id了。
看来插件的bangumi信息获取逻辑是bgm没有简介就不会写入id，也不会获取标题

这样应该算解决我的疑问了，非常感激！！

**Comment by kookxiang** [comment]
https://ci.appveyor.com/project/kookxiang/jellyfin-plugin-bangumi/builds/44528703/artifacts
使用这个版本覆盖一下，或者启用【始终根据文件名猜测集数】功能，应该能解决本问题

**Comment by mutsumi63** [comment]
> https://ci.appveyor.com/project/kookxiang/jellyfin-plugin-bangumi/builds/44528703/artifacts 使用这个版本覆盖一下，或者启用【始终根据文件名猜测集数】功能，应该能解决本问题

以下几次都是
ep的元数据获取是tmdb优先于bangumi
bangumiid指定975的情况
每次都会删除季度文件夹

Bangumi插件版本1.4.18.0 （三个选项均未选择的情况）
文件结构
海贼王--S21--E1020.MP4
海贼王--S21--E1021.MP4
海贼王--S21--E1022.MP4
海贼王--S21--E1023.MP4  未获取到bangumi epid
海贼王--S21--E1024.MP4
海贼王--S21--E1025.MP4 
海贼王--S21--E1026.MP4  未获取到bangumi epid
海贼王--S21--E1027.MP4  未获取到bangumi epid
海贼王--S21--E1028.MP4  未获取到bangumi epid
海贼王--S21--E1029.MP4  未获取到bangumi epid


Bangumi插件版本1.4.18.0（开启了【始终根据文件名猜测集数】）
文件结构 
海贼王--S21--E1020.MP4
海贼王--S21--E1021.MP4
海贼王--S21--E1022.MP4
海贼王--S21--E1023.MP4  未获取到bangumi epid
海贼王--S21--E1024.MP4
海贼王--S21--E1025.MP4 
海贼王--S21--E1026.MP4  未获取到bangumi epid
海贼王--S21--E1027.MP4  未获取到bangumi epid
海贼王--S21--E1028.MP4  未获取到bangumi epid
海贼王--S21--E1029.MP4  未获取到bangumi epid


Bangumi插件版本1.4.28.0 你发的那个build（三个选项均未选择的情况）
文件结构
海贼王--S21--E1020.MP4
海贼王--S21--E1021.MP4
海贼王--S21--E1022.MP4
海贼王--S21--E1023.MP4  未获取到bangumi epid
海贼王--S21--E1024.MP4
海贼王--S21--E1025.MP4 
海贼王--S21--E1026.MP4  未获取到bangumi epid
海贼王--S21--E1027.MP4  未获取到bangumi epid
海贼王--S21--E1028.MP4  未获取到bangumi epid
海贼王--S21--E1029.MP4  未获取到bangumi epid


Bangumi插件版本1.4.28.0 你发的那个build（开启了【始终根据文件名猜测集数】）
文件结构
海贼王--S21--E1020.MP4
海贼王--S21--E1021.MP4
海贼王--S21--E1022.MP4
海贼王--S21--E1023.MP4  未获取到bangumi epid
海贼王--S21--E1024.MP4
海贼王--S21--E1025.MP4 
海贼王--S21--E1026.MP4  未获取到bangumi epid
海贼王--S21--E1027.MP4  未获取到bangumi epid
海贼王--S21--E1028.MP4  未获取到bangumi epid
海贼王--S21--E1029.MP4  未获取到bangumi epid


四次结果一样 不知道会不会有缓存？我每次都删了季度文件夹的 换插件也重启了
日志看了下ep的index能识别到

建议测试样例写E1020-E1029试试 看看能不能复现

**Comment by chu-shen** [comment]
测了一下，我觉得可能的原因之一是bangumi api返回值问题

### 顺序

API返回值是乱序的

比如：EP1026查询的url是：https://api.bgm.tv/v0/episodes?subject_id=975&limit=50&offset=1006

返回的最后一个值是`1023`，小于`1026`，因此重新计算偏移值，导致新的查询里没有EP1026的数据 https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/ed1400e82b7c489f91d4113c63b8b0d580cdd622/Jellyfin.Plugin.Bangumi/BangumiApi.cs#L109

排序后测试没有问题：`var newResult = result.Data.OrderBy(x => x.Order);`

### “值丢失”

不清楚bangumi那边返回逻辑是啥，不过观察了下返回结果，offset是自带有前后结果的。这步是否没必要减去Offset？https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/ed1400e82b7c489f91d4113c63b8b0d580cdd622/Jellyfin.Plugin.Bangumi/BangumiApi.cs#L77

如果减去，则EP1023无结果，1022和1024都有：https://api.bgm.tv/v0/episodes?subject_id=975&limit=50&offset=1003

直接查的话则有

其他的剧集debug是没有问题的，至于为啥没有，不负责任猜测和jellyfin有关

**Comment by mutsumi63** [comment]
> 测了一下，我觉得可能的原因之一是bangumi api返回值问题
> 
> ### 顺序
> API返回值是乱序的
> 
> 比如：EP1026查询的url是：https://api.bgm.tv/v0/episodes?subject_id=975&limit=50&offset=1006
> 
> 返回的最后一个值是`1023`，小于`1026`，因此重新计算偏移值，导致新的查询里没有EP1026的数据
> 
> https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/ed1400e82b7c489f91d4113c63b8b0d580cdd622/Jellyfin.Plugin.Bangumi/BangumiApi.cs#L109
> 
> 排序后测试没有问题：`var newResult = result.Data.OrderBy(x => x.Order);`
> 
> ### “值丢失”
> 不清楚bangumi那边返回逻辑是啥，不过观察了下返回结果，offset是自带有前后结果的。这步是否没必要减去Offset？
> 
> https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/ed1400e82b7c489f91d4113c63b8b0d580cdd622/Jellyfin.Plugin.Bangumi/BangumiApi.cs#L77
> 
> 如果减去，则EP1023无结果，1022和1024都有：https://api.bgm.tv/v0/episodes?subject_id=975&limit=50&offset=1003
> 
> 直接查的话则有
> 
> 其他的剧集debug是没有问题的，至于为啥没有，不负责任猜测和jellyfin有关

加个type=0

**Comment by kookxiang** [comment]
确实跟返回的顺序有关，默认的返回顺序应该是条目创建的顺序，所以会导致跟 SP 混合之后解析错误
因为目前还没有好的办法自动识别是否是 SP，所以还不能单纯的写死 type

**Comment by kookxiang** [comment]
https://ci.appveyor.com/project/kookxiang/jellyfin-plugin-bangumi/builds/44530839/artifacts
试试这个版本？

**Comment by mutsumi63** [comment]
> https://ci.appveyor.com/project/kookxiang/jellyfin-plugin-bangumi/builds/44530839/artifacts 试试这个版本？

1023以外的都有了

**Comment by kookxiang** [comment]
这集创建时间很晚，还要往后翻一页才能匹配到，所以没匹配上

**Comment by kookxiang** [comment]
https://ci.appveyor.com/project/kookxiang/jellyfin-plugin-bangumi/builds/44531339/artifacts
这个版本应该 ok 了

**Comment by mutsumi63** [comment]
> https://ci.appveyor.com/project/kookxiang/jellyfin-plugin-bangumi/builds/44531339/artifacts 这个版本应该 ok 了

嗯 这个版本ok的了
