### ISSUE TITLE
插件不支持Jellyfin 10.8.0版本

### ISSUE THREAD

**Issue by fzlins** [kookxiang/jellyfin-plugin-bangumi#3]
可以安装1.3版本插件，但是系统提示不支持当前版本。

**Comment by fzlins** [comment]
![image](https://user-images.githubusercontent.com/100051558/167194802-6d84b631-9b64-41e3-b2e3-c31e797cc0d6.png)

**Comment by kookxiang** [comment]
https://github.com/jellyfin/jellyfin/commit/5732e6188c78e9e0de4a5557bfa9cfa64e05b506
新的 Jellyfin ABI 调整了，晚上我适配下
