### ISSUE TITLE
区分动画不同季

### ISSUE THREAD

**Issue by RanKKI** [kookxiang/jellyfin-plugin-bangumi#30]
遇到个情况，比如 [からかい上手の高木さん](https://bgm.tv/subject/347887) 有 3 季

S01E01 和 S02E01, S03E01 的 Episode ID 是一样的，在补全 metadata 的时候似乎没有对 Season 做处理。

**Comment by RanKKI** [comment]
仔细看了下代码和 API，API 不会返回季度。
所以只能通过放送日期中的年份区分，但 API 默认的返回是不带 `air_date` 字段，所以导致分类错误

**Comment by RanKKI** [comment]
思考了下另个问题， 分割放送的情况。
如 SPYxFamily 都是 S1，但是是分割放送，在 bgm.tv 是放在了另一个 subject id 下，
但 jellyfin 这边我更想放在 Season 1 一个文件夹下，但似乎一个文件夹的 Bangumi ID 只能有一个， 是否考虑支持多个 ID ？

如果可以这么搞，我可以做这部分～

**Comment by kookxiang** [comment]
jellyfin 不支持
个人推荐的方案是建一个 Season 1 Part 2 文件夹，这样 jellyfin 会把两个 season 1 的合并展示

**Comment by RanKKI** [comment]
> jellyfin 不支持 个人推荐的方案是建一个 Season 1 Part 2 文件夹，这样 jellyfin 会把两个 season 1 的合并展示

好，我去看看。
