### ISSUE TITLE
似乎无法获取元数据了

### ISSUE THREAD

**Issue by Archer-Tatsu** [kookxiang/jellyfin-plugin-bangumi#36]
已经手动设置了bangumi id，但是刷新以后元数据也不会更新，修改图片也不会列出来自bangumi的封面图。
之前成功从bangumi获取过封面图的番剧，现在也获取不到了。
在“识别”中输入bangumi id会返回空结果。（但是使用名字检索却能搜到bangumi的结果）
另外授权登录会返回Error processing request.

**Comment by kookxiang** [comment]
麻烦手动刷新一下元数据然后发下 log

**Comment by Archer-Tatsu** [comment]
今天试了下可以了，很奇怪，暂时当成是网络波动吧，我再观察下看看
