### ISSUE TITLE
对于大长篇集数的支持

### ISSUE THREAD

**Issue by Kuro96** [kookxiang/jellyfin-plugin-bangumi#40]
你好，我在使用中发现对于大长篇，例如[猫和老鼠](https://bangumi.tv/subject/25961)，似乎会出现把1xx集识别为xx集的情况，不知是否进行过适配？谢谢

**Comment by kookxiang** [comment]
麻烦提供下文件名

**Comment by Kuro96** [comment]
```bash
'001 - Puss Gets the Boot.mp4'
'010 - The Lonesome Mouse.mp4'
'161 - Purr-Chance to Dream.mp4'
```
类似这样的

**Comment by kookxiang** [comment]
插件默认用 jellyfin 自动识别的集数，确实可能不对
开启设置里面的【始终根据文件名猜测集数】可以解决
（不知道为啥现在修改配置后没法立即生效，需要手动重启下 jellyfin）

**Comment by Kuro96** [comment]
原来如此！感谢感谢！
