### ISSUE TITLE
登录但不同步进度

### ISSUE THREAD

**Issue by wzyboy** [kookxiang/jellyfin-plugin-bangumi#45]
考虑到 API 频率限制以及 #9 所提的需要登录后才能搜索的条目，是否可以提供一个只登录（并用 token 进行搜索）但是不同步观看进度的选项？

使用场景：

* 不希望里番观看进度同步到 Bangumi
* Jellyfin 有多个用户，不希望其他人的观看进度同步到管理员的账号

**Comment by kookxiang** [comment]
1. 未来会想办法区分里番，目前设置中有提供同步功能开关，或者也能在 bgm 中选择仅自己可见
2. 目前登录是跟着 Jellyfin 账号走的，不会同步别的用户的播放进度

**Comment by wzyboy** [comment]
诶？是我没找对地方吗…我看设置页面就只有 OAuth 与否的设置，并没有是否同步的设置啊…

![image](https://user-images.githubusercontent.com/459384/212580707-42ff1d4f-d917-49da-bcaa-74e4a9475f34.png)

**Comment by wzyboy** [comment]
感谢！原来如此

**Comment by chu-shen** [comment]
> * 不希望里番观看进度同步到 Bangumi
> * Jellyfin 有多个用户，不希望其他人的观看进度同步到管理员的账号

不希望NSFW被看到的话，先在bgm将条目标为「仅自己可见」。

现在不都是无法正确识别条目及集数，导致无法同步成功吗😂手动修改匹配的吗

**Comment by chu-shen** [comment]
非管理员账号怎么启用同步的啊，不是没法进控制台吗？

**Comment by wzyboy** [comment]
> 先在bgm将条目标为「仅自己可见」

咦，所以现在只有已经在 Bangumi 上收藏的条目才会同步吗？那我就放心了。因为我刚开始用 Jellyfin 管理动画，想要测试各种兼容性（码率、格式、字幕等），不希望在瞎点的过程中同步一堆进度上去……

> 非管理员账号怎么启用同步的啊，不是没法进控制台吗？

是我理解错了，我原以为这个功能是所有用户的进度都同步进同一个账号…

**Comment by chu-shen** [comment]
> 咦，所以现在只有已经在 Bangumi 上收藏的条目才会同步吗？那我就放心了。因为我刚开始用 Jellyfin 管理动画，想要测试各种兼容性（码率、格式、字幕等），不希望在瞎点的过程中同步一堆进度上去……
> 

不是收藏的才会同步，没收藏也会，bgm小组有个帖子就是这个问题（~~找不到了~~），所以NSFW最好先标「仅自己可见」

**Comment by wzyboy** [comment]
懂了，在更新版本可以关掉同步之前之前：

* 不要登录
* 不要乱点
* ~~不要看里番~~
