### ISSUE TITLE
移除Season季度名

### ISSUE THREAD

**Issue by chu-shen** [kookxiang/jellyfin-plugin-bangumi#47]
才注意到Season元数据修复了，赞👍

不过使用时发现季度名变成条目名，不再是原来的「第 N 季」

我个人是偏向使用「第 N 季」，不知道大家啥想法

---

移除`Name`和`OriginalTitle `：
https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/338f4a4d9d858fd4f3ed456042841292c6377f86/Jellyfin.Plugin.Bangumi/Providers/SeasonProvider.cs#L47

**Comment by kookxiang** [comment]
感觉显示第 x 季这种对于 SAO 这类不是很清晰？
不过确实可以给个开关就是

**Comment by chu-shen** [comment]
> 不过确实可以给个开关就是

我觉得可以👍，先过渡下
