### ISSUE TITLE
文件名解析

### ISSUE THREAD

**Issue by chu-shen** [kookxiang/jellyfin-plugin-bangumi#53]
## 目标

将文件名解析的工作分离出来，向用户提供两种解析器：
1. bangumi插件自带的解析器，与其他解析器互斥
2. 其他解析器

## 优点

1. 插件自带简单处理逻辑，无需额外操作即可获得较好效果
2. 兼容其他解析器，优势明显，可以提供更好的解析效果

## 应用场景

1. 动画标题识别
2. 复杂场景下的集数识别
3. SP识别👉https://github.com/kookxiang/jellyfin-plugin-bangumi/issues/33#issuecomment-1422664564

## 实现

1. bangumi插件调整解析逻辑，分离自带的解析器
2. 集成其他解析器

解析器我推荐现成的[AnitomySharp](https://github.com/chu-shen/AnitomySharp)，也可以选择[原版](https://github.com/erengy/anitomy)

AnitomySharp提供以下类别的解析结果👉[ElementCategory](https://anitomysharp.chushen.xyz/api/AnitomySharp.Element.ElementCategory.html)

使用方法见👉[Anitomy.cs](https://github.com/kookxiang/jellyfin-plugin-bangumi/blob/master/Jellyfin.Plugin.Bangumi/Anitomy.cs#L14)

大家觉得怎么样，讨论一下是否可行

**Comment by kookxiang** [comment]
拆出来没问题
代码是希望放在本仓库内还是说做一个动态加载库的逻辑？

**Comment by chu-shen** [comment]
> 拆出来没问题 代码是希望放在本仓库内还是说做一个动态加载库的逻辑？

自带的解析器由bangumi插件维护，我觉得应该没必要单独拆分出来

其他解析器（如：AnitomySharp）由提供方维护，不合并到bangumi插件，动态加载
