### ISSUE TITLE
插件抓取结果失败

### ISSUE THREAD

**Issue by Hyaclnth** [kookxiang/jellyfin-plugin-bangumi#60]
确认网络环境良好，在服务器上通过浏览器能正常访问bgm.tv，但是经常性出现插件抓取不到剧集的问题，求助下大佬
[jellyfin.log](https://github.com/kookxiang/jellyfin-plugin-bangumi/files/11149485/jellyfin.log)

**Comment by kookxiang** [comment]
设置里面加下超时时间看看能否解决？

**Comment by Hyaclnth** [comment]
> 设置里面加下超时时间看看能否解决？

我有尝试过设置超时时间，即使是最大1分钟也还是一样的问题

**Comment by Hyaclnth** [comment]
很奇怪的问题，也不知道怎么出现的
反复尝试+摸索，最后发现手动清除Cache文件后正常了，到目前为止没有再次出现这个问题，输入ID都是秒识别

**Comment by t-zhan** [comment]
同样的问题，已经设置超时1分钟，像 @Hyaclnth 说的清除cache重启emby后第一次可以刮削成功，之后就提示time out
