### ISSUE TITLE
[Feature Request] 自动设置节目到「在看」

### ISSUE THREAD

**Issue by RanKKI** [kookxiang/jellyfin-plugin-bangumi#61]
遇到的情况是，新番看完了，发现 bangumi 这边因为没有设置到「在看」，看的记录都没有同步

```
Jellyfin.Plugin.Bangumi.Model.ServerException: Bad Request: you need to add subject to your collection first
```

如果遇到这种报错，可以发请求把该 subject 设置为在看，再设置某一集到看过，体验会好一些。

**Comment by kookxiang** [comment]
[/v0/users/-/collections/{subject_id}](https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/patchUserCollection)
试了下这个接口不可用的样子

**Comment by RanKKI** [comment]
https://github.com/bangumi/server/blob/f9d97244a1238e0b5911538c43f40d8a3085ccaf/web/handler/user/patch_subject_collection.go#L87

我看了下， 目前是没有 `增加某节目到 collections` 的接口，只有修改，因此会报错 `subject not collected`。

去那边提个 issue，看看能不能加这个 API

**Comment by kookxiang** [comment]
#66
