### ISSUE TITLE
每一季都有sp的多季剧集有推荐的整理命名吗

### ISSUE THREAD

**Issue by deadblue0910** [kookxiang/jellyfin-plugin-bangumi#68]
[看见这个可以和tmdb合用](https://github.com/kookxiang/jellyfin-plugin-bangumi/wiki/%E5%8F%82%E8%80%83%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84)
-
一级文件夹是动画标题，二级文件夹是每一季，二级文件夹下不好再建Specials了
第一季的SP放到season 1下，season 1 tmdb的数据是正确的，bangumi识别成了第二季，几个sp也识别为了第二季的sp，手动输入id后，季的识别正确了，几个sp的还是第二季；元数据只开bangumi，结果一样
或者把第一季的sp单独建一个新妹魔王的契约者 - Specials的文件夹？
```
新妹魔王的契约者 (2015)
      │── season 1 # TMDB
      │       ├── 新妹魔王的契约者 S01E01.mkv
      │       ├── 新妹魔王的契约者 S02E02.mkv
      │       ├── SP 01.mkv
      │── 新妹魔王的契约者 - Specials  # bangumi id
      │       ├── SP 01.mkv
      │       ├── SP 02.mkv
      │
      │── season 2  # TMDB
      │       ├── 新妹魔王的契约者 S02E01.mkv
      │       ├── 新妹魔王的契约者 S02E02.mkv
      │       ├── ~~SP 01.mkv~~
      │── 新妹魔王的契约者 BURST - Specials # bangumi id
      │       ├── SP 01.mkv
      │       ├── SP 02.mkv
      │
      │──  新妹魔王的契约者 OAD  # bangumi id
      │       ├── 新妹魔王的契约者 OAD 01.mkv
      │       ├── 新妹魔王的契约者 OAD 02.mkv
```

**Comment by kookxiang** [comment]
jellyfin 的 SP 统一算 Season 0，还不支持多季 SP

**Comment by deadblue0910** [comment]
请问下元数据只开bangumi的情况下， 新妹魔王的契约者 (2015)   --   season 1  --  新妹魔王的契约者 S01EXX.mkv，season 1   bangumi识别成了第二季（新妹魔王的契约者 BURST），这个是哪地方设置不对吗？把season1 的季id改了之后刷新，集的识别依然是第二季的
![Snipaste_2023-05-11_13-09-53](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/48860218/d51c1879-a262-4b37-bc24-dbf4b1a8bded)
![Snipaste_2023-05-11_13-10-03](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/48860218/7317a8fc-c233-43d0-80bd-92c2ed18d661)
![Snipaste_2023-05-11_13-11-53](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/48860218/4bc8a97f-96c7-48f3-ac4d-70153c646b82)

**Comment by kookxiang** [comment]
启用 “始终根据配置的 Bangumi ID 获取元数据” 后不会再判断季和集之间的匹配关系，会直接拉取元数据
可以关掉这个开关再试
