### ISSUE TITLE
无法刮削连载超过100话的番剧

### ISSUE THREAD

**Issue by KeepNaivety3** [kookxiang/jellyfin-plugin-bangumi#7]
刮削[KERORO军曹](https://bgm.tv/subject/1849/ep)前100话能正常获取标题等信息，100话后无法刮削到数据

谢谢回复，另外想询问一下有关于SP的刮削问题，部分番剧包含SP OP ED等，能否支持一下SP的刮削？
例如
- SP第零话：[鲁邦三世 PART6](https://bgm.tv/subject/337430) ，[辉夜大小姐第三季](https://bgm.tv/subject/317613)
- 中间插入SP：[恋爱小行星](https://bgm.tv/subject/276150)
- SP最后一话：[无职转生 第二部分](https://bgm.tv/subject/325585)
- 单独计数的SP：[赛马娘 Pretty Derby](https://bgm.tv/subject/212003)，[公主代理人剧场版](https://bgm.tv/subject/244928)
- 包含OP或者ED：[冰菓](https://bgm.tv/subject/27364)

**Comment by kookxiang** [comment]
1.4.1 已修正超过 100 条的问题
另外可以试试新版本 SP 识别效果 https://github.com/kookxiang/jellyfin-plugin-bangumi/wiki/%E5%8F%82%E8%80%83%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84
