### ISSUE TITLE
似乎无法使用，显示NotSupported

### ISSUE THREAD

**Issue by TAN-Z-H** [kookxiang/jellyfin-plugin-bangumi#79]
我按照网上的一篇帖子进行操作，但最终显示NotSupported

系统版本：DSM 7.2-64570 Update 1
jellyfin ：10.8.0
帖子链接 ：https://www.himiku.com/archives/deploy-a-more-comfortable-animation-library-with-jellyfin-and-bangumi.html

**Comment by kookxiang** [comment]
请使用 Jellyfin 官方镜像

**Comment by TAN-Z-H** [comment]
明白，多谢指导
