### ISSUE TITLE
对搜索结果进行排序

### ISSUE THREAD

**Issue by chu-shen** [kookxiang/jellyfin-plugin-bangumi#8]
BGM返回的第一个结果并不是最匹配的，导致自动更新元数据时匹配到错误条目

不清楚BGM那边是否有计划更新返回逻辑。从网上**copy**了份排序代码，测试效果还行👉https://github.com/chu-shen/jellyfin-plugin-bangumi/releases/tag/2.0.0

希望能返回比较准确的结果，不然一个一个修改回来太辛苦了😰

附测试动画：
- ガンダムビルドファイターズトライ
- マジンガーZ

**Comment by kookxiang** [comment]
1.4.1 验证 OK
