### ISSUE TITLE
询问，sp该怎么命名

### ISSUE THREAD

**Issue by banned2054** [kookxiang/jellyfin-plugin-bangumi#80]
举个例子，像这个动画[向山进发 第二季](https://bgm.tv/subject/86670)，里面sp有两集，分别是6.5集和25集，
那我是命名成
`向山进发 第二季 specials E06.5.mp4`和`向山进发 第二季 specials E25.mp4`
还是
`向山进发 第二季 specials E01.mp4`和`向山进发 第二季 specials E02.mp4`
尝试开了`始终根据配置的 Bangumi ID 获取元数据`，但不知道怎么修改单集的元数据，直接去改元数据里单集的bangumi id吗，保存后要什么时候才能生效

**Comment by kookxiang** [comment]
集数按 bgm 的写就好，比如 SP06.5 SP25
如果不行我晚上测试下

启用始终按 bgmid 获取后插件会以元数据中配置的 id 为准，用于极端情况一直获取不对或者无法推断集数的情况

**Comment by banned2054** [comment]
好的，在元数据编辑页面刷新下就好了，感谢

**Comment by banned2054** [comment]
不过我看了我存的所有动画，所有的.5集都没有被识别出来，例如xxxx E14.5.mp4，就会被识别成14集放到正剧中，必须要手动调整id并刷新元数据才可以

**Comment by misaka10843** [comment]
> 不过我看了我存的所有动画，所有的.5集都没有被识别出来，例如xxxx E14.5.mp4，就会被识别成14集放到正剧中，必须要手动调整id并刷新元数据才可以

这似乎是jellyfin的问题，并不支持识别小数点
![image](https://github.com/kookxiang/jellyfin-plugin-bangumi/assets/69132853/da55e703-8a8c-4135-9d5f-3bf56c4868f4)
