### ISSUE TITLE
当条目只有一个 EP 时强制匹配单集

### ISSUE THREAD

**Issue by everpcpc** [kookxiang/jellyfin-plugin-bangumi#90]
如一些 OVA/剧场版，通常文件名不会带上 ep01 之类的字样，无法简单识别。

**Comment by Rivers47** [comment]
即便勾选了始终根据文件名猜测集数并且不使用AnitomySharp，文件夹里只有一个视频文件的时候仍然无法对应上BGM唯一的单集……
